# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"

  # config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "private_network", ip: "192.168.33.10"

  # config.vm.synced_folder "../data", "/vagrant_data"

  config.berkshelf.berksfile_path = "../chef-repo/Berksfile"
  config.berkshelf.enabled = true
  config.omnibus.chef_version = :latest
  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "../chef-repo/cookbooks"
    chef.run_list = [
      'recipe[build-essential]',
      'recipe[nodejs]',
      'recipe[ruby]',
      'recipe[bundler]',
      'recipe[git]',
      'recipe[java]',
      'recipe[chrome]',
      # 'recipe[protractor-selenium-server]',
      "recipe[chef-repo::default]"
    ]
  end

end
